framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            #OOD\Core\Shared\Domain\Bus\Command\Command: sync
            #OOD\Core\Shared\Domain\Bus\Query\Query: sync
#            OOD\Core\Shared\Domain\Bus\Event\Event: broadcast
            #OOD\Core\Shared\Domain\Bus\Event\EventReceived: sync

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    #- App\Core\Component\Infrastructure\Messenger\Middleware\HandleMessageDomainEventMiddleware