system_controllers:
    resource:
        path: ../src/System/Infrastructure/Adapters/Driving/HTTP/
        namespace: App\System\Infrastructure\Adapters\Driving\HTTP
    type: attribute

kernel:
  resource: ../src/Kernel.php
  type: annotation